// <auto-generated />
using System;
using Farmazon.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Farmazon.DAL.Migrations
{
    [DbContext(typeof(FarmaContext))]
    [Migration("20190701234436_Farmazon.DAL.FarmaContextSeed")]
    partial class FarmazonDALFarmaContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Farmazon.DAL.Products", b =>
                {
                    b.Property<long>("productId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("productName");

                    b.Property<long?>("productOwnerId");

                    b.Property<string>("productOwnerLastName");

                    b.Property<string>("productOwnerName");

                    b.HasKey("productId");

                    b.ToTable("Product");

                    b.HasData(
                        new { productId = 1L, productName = "Monitor 27", productOwnerId = 1L, productOwnerLastName = "Ecer", productOwnerName = "Enes" },
                        new { productId = 2L, productName = "Klavye", productOwnerId = 0L, productOwnerLastName = "", productOwnerName = "" },
                        new { productId = 3L, productName = "Mekanik Klavye", productOwnerId = 1L, productOwnerLastName = "Ecer", productOwnerName = "Enes" },
                        new { productId = 4L, productName = "Monitor 23", productOwnerId = 2L, productOwnerLastName = "Arslan", productOwnerName = "Oguzcan" }
                    );
                });

            modelBuilder.Entity("Farmazon.DAL.Users", b =>
                {
                    b.Property<long>("userId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateOfBirth");

                    b.Property<string>("email");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("phoneNumber");

                    b.Property<string>("userPassword");

                    b.HasKey("userId");

                    b.ToTable("User");

                    b.HasData(
                        new { userId = 1L, dateOfBirth = new DateTime(1995, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), email = "email@mail.com", firstName = "Enes", lastName = "Ecer", phoneNumber = "11223344556677", userPassword = "pW1234!" },
                        new { userId = 2L, dateOfBirth = new DateTime(1996, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), email = "email2@mail.com", firstName = "Oguzcan", lastName = "Arslan", phoneNumber = "", userPassword = "Pass1234!" },
                        new { userId = 3L, dateOfBirth = new DateTime(1995, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), email = "", firstName = "Ali", lastName = "Cennet", phoneNumber = "113344667799852", userPassword = "parola789" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
